DECLARE
    TRIP_DATE DATE;
    HOTEL_FOR_TRIP INTEGER;
BEGIN
-- DELETE INDEX RESPONSIBLE FOR UNIQUENESS OF GUIDE FOR EACH TRIP
DELETE INDEX TRIP__IDX;
-- CITY/COUNTRY GENERATION --
FOR loop_counter IN 1..20 LOOP
    INSERT INTO "CITY" (CITY_ID, CITY, COUNTRY)
    VALUES (
        loop_counter,
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(8, 20)),
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(8, 20))
    );
END LOOP;
END;

BEGIN
-- ADDRESS GENERATION -- 
FOR loop_counter IN 1..160 LOOP
    INSERT INTO "ADDRESS" (ADDRESS_ID, STREET, STREET_NUMBER, APARTMENT_NUMBER, ZIP_CODE, CITY_ID)
    VALUES (
        loop_counter, 
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(6, 20)), 
        FLOOR(DBMS_RANDOM.VALUE(1, 200)), 
        FLOOR(DBMS_RANDOM.VALUE(1, 200)),
        TO_CHAR(FLOOR(DBMS_RANDOM.VALUE(0, 10))) || TO_CHAR(FLOOR(DBMS_RANDOM.VALUE(0, 10))) || '-' ||  TO_CHAR(FLOOR(DBMS_RANDOM.VALUE(1000, 9999))),
        DBMS_RANDOM.VALUE(1, 20)
    );
END LOOP;
END;

BEGIN
-- CLIENT GENERATION -- 
FOR loop_counter IN 1..100 LOOP
    INSERT INTO "CLIENT" (CLIENT_ID, NAME, SURNAME, MAIL, TELEPHONE, ADDRESS_ID)
    VALUES (
        loop_counter,
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(3, 10)), 
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(6, 15)),
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(4, 10)) || '@gmail.com',
        FLOOR(DBMS_RANDOM.VALUE(100000000, 999999999)),
        loop_counter
    );
END LOOP;
END;

BEGIN
-- EMPLOYEE GENERATION -- 
FOR loop_counter in 1..20 LOOP
    INSERT INTO "GUIDE" (GUIDE_ID, NAME, SURNAME, MAIL, TELEPHONE, ADDRESS_ID)
    VALUES (
        loop_counter,
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(3, 10)), 
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(6, 15)),
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(4, 10)) || '@gmail.com',
        FLOOR(DBMS_RANDOM.VALUE(100000000, 999999999)),
        loop_counter+100
    );
    INSERT INTO "TRAVEL_AGENT" (AGENT_ID, NAME, SURNAME, MAIL, TELEPHONE, ADDRESS_ID)
    VALUES (
        loop_counter,
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(3, 10)), 
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(6, 15)),
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(4, 10)) || '@gmail.com',
        FLOOR(DBMS_RANDOM.VALUE(100000000, 999999999)),
        loop_counter+120
    );
END LOOP;
END;

BEGIN
-- HOTEL GENERATION --
FOR loop_counter in 1..20 LOOP
    INSERT INTO "HOTEL" (HOTEL_ID, NAME, STARS, ADDRESS_ID)
    VALUES (
        loop_counter,
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(10, 20)),
        FLOOR(DBMS_RANDOM.VALUE(3, 6)),
        loop_counter+140
    );
END LOOP;
END;

BEGIN
-- TRIP, TRANSPORT AND HOTEL  GENERATION --
FOR loop_counter in 1..40 LOOP
    TRIP_DATE :=  TO_DATE(TRUNC(DBMS_RANDOM.VALUE(TO_CHAR(DATE '2022-01-01','J') , TO_CHAR(DATE '2023-11-30','J'))),'J');
    HOTEL_FOR_TRIP := FLOOR(DBMS_RANDOM.VALUE(1, 20));
    INSERT INTO "TRANSPORT" (TRANSPORT_ID, MEAN_OF_TRANSPORT, PLACE, DATE_OF_DEPARTURE)
    VALUES (
        loop_counter,
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(5, 10)),
        DBMS_RANDOM.STRING('A', DBMS_RANDOM.VALUE(10, 20)),
        TRIP_DATE
    );
    INSERT INTO "TRIP" (TRIP_ID, DESTINATION, PRICE, STARTING_DATE, ENDING_DATE, MAXIMAL_NUMBER_OF_PARTICIPANTS, TRANSPORT_ID, GUIDE_ID)
    VALUES (
        loop_counter,
        TO_CHAR(
            (SELECT CITY.COUNTRY
            FROM HOTEL
            JOIN ADDRESS ON HOTEL.ADDRESS_ID = ADDRESS.ADDRESS_ID
            JOIN CITY ON ADDRESS.CITY_ID = CITY.CITY_ID
            WHERE HOTEL_ID = HOTEL_FOR_TRIP)
        ),
        FLOOR(DBMS_RANDOM.VALUE(1000.00, 9999.00)),
        TRIP_DATE,
        TRIP_DATE + TRUNC(DBMS_RANDOM.VALUE(7, 15)),
        FLOOR(DBMS_RANDOM.VALUE(20, 99)),
        loop_counter,
        FLOOR(DBMS_RANDOM.VALUE(1, 20))
    );
    INSERT INTO "TRIPHOTELRELATION" (HOTEL_ID, TRIP_ID)
    VALUES (
        HOTEL_FOR_TRIP,
        loop_counter
    );
END LOOP;
END;

BEGIN
-- TRANSACTION GENERATION -- 
FOR loop_counter in 1..100 LOOP
    INSERT INTO "TRANSACTION" (TRANSACTION_ID, PAYMENT_STATUS, CLIENT_ID, AGENT_ID, TRIP_ID)
    VALUES (
        loop_counter,
        FLOOR(DBMS_RANDOM.VALUE(0, 2)),
        loop_counter,
        DBMS_RANDOM.VALUE(1, 20),
        DBMS_RANDOM.VALUE(1, 40)
    );
END LOOP;
END;