SELECT TRIP.TRIP_ID, TRIP.DESTINATION  
FROM TRIP
WHERE TRIP.ENDING_DATE - TRIP.STARTING_DATE > 7 AND TRIP.ENDING_DATE - TRIP.STARTING_DATE < 14;

SELECT HOTEL.HOTEL_ID, HOTEL.NAME
FROM HOTEL
WHERE HOTEL.STARS = 4 OR HOTEL.STARS = 5;

SELECT ROUND(AVG(PRICE), 2) AVERAGE_PRICE, ROUND(MAX(PRICE), 2) MAX_PRICE, ROUND(MIN(PRICE), 2) MIN_PRICE
FROM TRIP;

SELECT COUNT(HOTEL.NAME), HOTEL.STARS
FROM HOTEL
GROUP BY STARS;

SELECT TRAVEL_AGENT.SURNAME, COUNT(TRANSACTION.TRANSACTION_ID) AS NUMBER_OF_SOLD_TRIPS
FROM (TRANSACTION
RIGHT JOIN TRAVEL_AGENT ON TRANSACTION.AGENT_ID = TRAVEL_AGENT.AGENT_ID)
GROUP BY TRAVEL_AGENT.SURNAME
HAVING COUNT(TRANSACTION.TRANSACTION_ID) > 5;

SELECT TRIP.DESTINATION, COUNT(TRANSACTION.CLIENT_ID) AS NUMBER_OF_CLIENTS_IN_TRIP
FROM TRIP
LEFT JOIN TRANSACTION ON TRIP.TRIP_ID = TRANSACTION.TRIP_ID
GROUP BY TRIP.DESTINATION
ORDER BY NUMBER_OF_CLIENTS_IN_TRIP DESC;

SELECT COUNT(TRANSACTION.CLIENT_ID), TRANSACTION.TRIP_ID 
FROM TRANSACTION
GROUP BY TRIP_ID; 

SELECT * 
FROM CLIENT 
WHERE CLIENT.CLIENT_ID IN (
    SELECT CLIENT.CLIENT_ID
    FROM TRANSACTION
    WHERE TRANSACTION.TRANSACTION_ID BETWEEN 1 AND 10
);

SELECT *
FROM TRAVEL_AGENT
WHERE EXISTS (
    SELECT TRANSACTION.AGENT_ID FROM TRANSACTION
    WHERE TRANSACTION.AGENT_ID=TRAVEL_AGENT.AGENT_ID
);

SELECT CITY.COUNTRY, CITY.CITY
FROM HOTEL 
JOIN ADDRESS ON HOTEL.ADDRESS_ID = ADDRESS.ADDRESS_ID
JOIN CITY ON ADDRESS.CITY_ID = CITY.CITY_ID
WHERE HOTEL.STARS=5;